version: "3.9"  # optional since v1.27.0
services:
  rest-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "es-service"
    environment:
      ES_HOST: es-service
      ES_PORT: 9200
      ES_USER: elastic
      ES_PASSWORD: $ES_PASSWORD
  es-service:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1     
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=$ES_PASSWORD
      - xpack.security.enabled=true
    volumes:
      - es_data:/usr/share/elasticsearch/data
volumes:
  es_data:
    driver: local